### PR TITLE
Use the DealerDirect Composer PHPCS plugin

### LINKED ISSUE #7: Update WPCS to 1.0.0
Looks like a major release came out: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/1.0.0

We should look into updating.

### LINKED ISSUE #9: phpcs fail if installing globably
I know the purpose is installing it as a dependency, but I just tried to install this globally to be able to user on a project that hasn't included it yet and it failed with the following error:

```
ERROR: the "10up-Default" coding standard is not installed. PHP Fatal error:  Uncaught UnexpectedValueException: DirectoryIterator::__construct(vendor/10up/phpcs-composer/10up-Default): failed to open dir: No such file or directory in /home/nicholas_io/.config/composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php:2141
```

The reason has to do with the relative paths to the vendor dir that assumes a local installation.

I was able to get a quick hotfix for this by setting the config path dynamically based on the vendor dir (this should be the safest way to set the path I believe).

```
$vendor = $this->composer->getConfig()->get('vendor-dir');
$this->PHPCS_CONFIG_PATH = sprintf('%1$s/10up/phpcs-composer,%1$s/wp-coding-standards/wpcs,%1$s/wimg/php-compatibility', $vendor);
```

I also had to comment out the rule below as it was giving me an error about not being able to find that rule (apparently extending a specific a rule still doesn't work with the fix above when installing globally):
```
<!--<rule ref="WordPress.WP.I18n.MissingTranslatorsComment">
		<type>warning</type>
</rule>-->
```

Any thoughts on this? I didn't submit a PR request as I'm not sure what is the best way to fix this.

### LINKED ISSUE #10: IDE Integration - PHPStorm
I installed this for an existing project to be used with `lint-staging` and while the automated process worked great, I was not able to get PHPStrom to use the ruleset for inline notifications.

Using the instructions in the readme,  I was getting errors similar to #9.

I was able to get PHPStorm to indicate the same errors inline that are flagged it the scan by creating a custom `ruleset.xml` file that contained only the rules contains in the 10up-Default/ruleset.xml file of this repo.

I'm not sure if this is specific to my setup ( I have wpcs setup globally ) but wanted to flag it. Perhaps, we just need to update the readme to address this edge-case?

### LINKED ISSUE #15: Suggestion: use the DealerDirect Composer PHPCS plugin
The `dealerdirect/phpcodesniffer-composer-installer` package - https://github.com/DealerDirect/phpcodesniffer-composer-installer - can take care of setting the PHPCS `installed_paths` config for you, rather than doing so using your own `PHPCSConfig.php`.

Generally speaking, a ruleset package like this would `suggest` the package and dependents should `require --dev` it. However, I imagine it will work just as well if this package would `require` it.

### PR DESCRIPTION
**Pull request by sudar**
This PR changes the composer project type to `phpcodesniffer standard` and uses the DealerDirect Composer PHPCS plugin instead of trying to set the default ruleset and installed paths using custom PHP code.

This was originally suggested by @jrfnl in #15 

This approach has the following advantages.

- Removes the need for custom PHP code
- Makes it easy to use with composer
- Fixes compatibility issues with PhpStorm (Fix #10)
- Fixes compatibility issues when phpcs is installed globally (Fix #9)

The following tickets can be closed once this PR is merged.

- Fix #7 
- Fix #9 
- Fix #10 
- Fix #15

### CODE REVIEW

**Comment by petenelson** [comment]
Not sure if it should be part of this PR, but noticed the https://packagist.org/packages/wimg/php-compatibility package is flagged as abandoned.

**Comment by jrfnl** [comment]
@petenelson That is addressed in PR #14 which has been open for 4 months now.

**Comment by sudar** [comment]
@ChaosExAnima @tlovett1 

Any change of getting this merged soon? Merging this can close lot of existing open issues and make the package more easy to use for lot of people.

Also meanwhile do let me know if I can be of any help.

**Comment by ChaosExAnima** [comment]
I'm fine with it. @tlovett1, are you good with it?

**Comment by tlovett1** [comment]
Works for me.

**Pull request merged**
