### PR TITLE
Use PHPCompatibilityWP and testVersion for PHP 7.0 and above.

### PR DESCRIPTION
**Pull request by samikeijonen**
This is replacement for #14 since I didn't know how to modify to original PR.

### CODE REVIEW

**Comment by samikeijonen** [comment]
## Notes

I added also `<config name="testVersion" value="7.0-"/>` and instruction in readme how to overwrite it in a project. That's because I didn't find any info about using `PHPCS_PHP_VERSION`.

@jrfnl would this be the correct usage of PHP version? This is the one that I have used myself.

Here is more info about [checking compatibility with specific PHP version](https://github.com/PHPCompatibility/PHPCompatibility#sniffing-your-code-for-compatibility-with-specific-php-versions).

## How this have been tested.

In theme scaffold `composer.json` I added these:

```
  "repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/samikeijonen/phpcs-composer-1"
    }
  ],
  "require-dev": {
    "10up/phpcs-composer": "dev-fix/phpcompatibility-wp"
  },
```
Then run `composer up` to get 10up PHPCS from my branch.

Then run `./vendor/bin/phpcs .` and `composer lint`.

I didn't notice any issue.

**Comment by samikeijonen** [comment]
@jrfnl Thanks for feedback!

- In cdbee28 I changed URL to PHPCompatibilityWP.
- In 6134f49 I updated PHPCS to `3.4.0`.
- In 4622ea7 I added extra note about overruling PHP version check using command-line only.
- In 12d83f8 I updated `composer.lock` file.

**Comment by samikeijonen** [comment]
@tlovett1 Do you want to review this one?

**Comment by samikeijonen** [comment]
@tlovett1 I have tested couple of times against theme scaffold like [outlined in this comment](https://github.com/10up/phpcs-composer/pull/17#issuecomment-457828304).

**Comment by ChaosExAnima** [comment]
Sounds good to me. Merging.

**Pull request merged**
